In [4]:
import numpy as np

In [6]:
#1.np.random.random生成N行M列的数组，其中元素值为0-1的随机数
d=np.random.random((2,3))
d

array([[0.29540213, 0.58072479, 0.4035937 ],
       [0.85043997, 0.57555037, 0.81086982]])

In [7]:
#2.使用np.array来创建数组
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [8]:
#3.使用np.arange来创建数组
b = np.arange(0,10)
b = np.arange(0,10,2)#2为步长
b

array([0, 2, 4, 6, 8])

In [15]:
#4.使用np.random.randint来创建一个N行N列的数组，其中元素值的范围可以通过前面两个参数来定
c = np.random.randint(0,9,size=(4,4))
c

array([[4, 7, 8, 7],
       [5, 7, 0, 8],
       [5, 0, 0, 1],
       [2, 5, 4, 2]])

In [19]:
#5.使用函数生成特殊的数组
a1 = np.zeros((2,2))
a2 = np.ones((3,2))
a3 = np.full((2,2),8)#生成一个所有元素都是8的2行2列的元素
a4 = np.eye(3)#生成一个主对角线为1，其他元素为0的3x3的矩阵

print("a1:",a1)
print("a2:",a2)
print("a3:",a3)
print("a4:",a4)

a1: [[0. 0.]
 [0. 0.]]
a2: [[1. 1.]
 [1. 1.]
 [1. 1.]]
a3: [[8 8]
 [8 8]]
a4: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
